#多环境 , 使用部署上线后的数据库 , 打成jar包后  根据 --spring.profiles.active=prod  使用application-prod.yml覆盖application.yml

server:
  port: 8080
  servlet:
    session:
      timeout: 86400 #一天 单位s
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.88.100:3306/usercenter?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: usercenter
    password: 123456